"""
protocol
"""
from typing import Protocol
from pathlib import Path

from .models import AccountData, AccountFiles, AccountMeta

class AccountInterface(Protocol):
    def init_new_acc(self) -> AccountMeta:
        ...
    def ask_account_info(self) -> AccountData:
        ...
    def generate_acc_data(self, data: AccountData) -> None:
        ...
    def load_acc_data(self, selector: str) -> AccountData:
        ...
    def load_acc_files(self, meta: AccountMeta) -> AccountFiles:
        ...
    def list_acc(self) -> dict[str, AccountMeta]:
        ...
    def update_acc(self, data: AccountData, files: AccountFiles) -> None:
        ...
    def rm_acc(self, meta: AccountMeta) -> None:
        ...
    def check_acc(self, path: Path) -> bool:
        ...
  
